global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # 컨테이너별 CPU 사용률 모니터링
  - job_name: 'cadvisor'
    static_configs:
      # Docker 네트워크에서 서비스 이름과 cAdvisor 기본 포트(8080) 사용
      - targets: ['msa-perf-cadvisor:8080']
  
  # HOST 지표 모니터링
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['msa-perf-node-exporter:9100']
  
  # Flask Gateway 모니터링
  # - job_name: 'flask-gateway'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['msa-perf-flask-gateway:5000']
  
  # Go Core 모니터링
  # - job_name: 'gocore'
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ['msa-perf-gocore:8080']
  
  